# This file was generated by the {rix} R package v0.15.8 on 2025-04-04
# with following call:
# >rix(r_ver = "4.4.0",
#  > r_pkgs = c("dplyr",
#  > "kableExtra",
#  > "magrittr",
#  > "desc",
#  > "purrr",
#  > "renv",
#  > "quarto",
#  > "pkglite"),
#  > system_pkgs = c("dejavu_fonts",
#  > "quarto"),
#  > tex_pkgs = c("amsmath",
#  > "framed",
#  > "multirow",
#  > "wrapfig",
#  > "tabu",
#  > "threeparttable",
#  > "threeparttablex",
#  > "environ",
#  > "makecell",
#  > "tcolorbox",
#  > "tikzfill",
#  > "pdfcol",
#  > "fontawesome5"),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > print = TRUE)
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2024-04-29.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      desc
      dplyr
      kableExtra
      magrittr
      pkglite
      purrr
      quarto
      renv;
  };
  
  tex = (pkgs.texlive.combine {
    inherit (pkgs.texlive) 
      scheme-small
      amsmath
      environ
      fontawesome5
      framed
      makecell
      multirow
      pdfcol
      tabu
      tcolorbox
      threeparttable
      threeparttablex
      tikzfill
      wrapfig;
  });
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      dejavu_fonts
      glibcLocales
      nix
      quarto
      R
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs tex  system_packages   ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
